import Header from "./components/Header";
import "./globals.css";


export const metadata = {
  title: "Track Your Works",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body data-theme="light" className="w-full">
        <div className="container mx-auto">
        <Header />
        {children}
        </div></body>
    </html>
  );
}
